# -*- coding: utf-8 -*-
"""Cópia de Olá, este é o Colaboratory

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1sMm5z4leVe6-PRDVwD7bCuP2OzpuLEGp
"""

n1 = 2 
n2 = 5 
n3 = 4 
if n1 < n2: 
    n3 = n1+n2
n3

nome = 'detergente'
print(len(nome))

print(nome[0:10])

a = 10
b = 3 
a= b
c = a+b 
b = 0 
b = 0 
d = a + b
print (f' valor da variavel {c}')